# Generated by Django 5.2.6 on 2025-10-15 15:10

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_learns_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('summery_description', models.CharField(verbose_name='خلاصه پست')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='user.bloger', verbose_name='بلاگر')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
