# Generated by Django 5.2.6 on 2025-10-15 15:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]


