# Generated by Django 5.2.6 on 2025-10-16 07:40

import django_ckeditor_5.fields
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='blog/main_image/', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='بدنه اصلی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت'),
        ),
    ]
