# Generated by Django 5.2.6 on 2025-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
