# Generated by Django 5.2.6 on 2025-10-16 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
        ('user', '0002_user_learns_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-create'], name='blog_post_create_d4c0ab_idx'),
        ),
    ]
