# Generated by Django 5.2.6 on 2025-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_post_blog_post_create_d4c0ab_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summery_description',
            field=models.CharField(max_length=500, verbose_name='خلاصه پست'),
        ),
    ]
