# Generated by Django 5.2.6 on 2025-10-11 09:33

import django_jalali.db.models
import django_resized.forms
import learn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='FilmScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سرفصل',
                'verbose_name_plural': 'سرفصل ها',
                'ordering': ['create'],
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('summery_description', models.TextField(max_length=250, verbose_name='خلاصه توضیحات')),
                ('description', models.TextField(max_length=4000, verbose_name='توضیحات')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='learns/images/%Y')),
                ('score', models.FloatField(verbose_name='امتیاز')),
                ('learn_time', models.PositiveIntegerField(verbose_name='مدت زمان آموزش')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('precent_off', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('discount_price', models.PositiveIntegerField(verbose_name='قیمت نهایی')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش ها',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='LearnFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(max_length=1200, verbose_name='توضیحات')),
                ('film', models.FileField(upload_to=learn.models.create_url_for_film, verbose_name='فیلم')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('number_score', models.FloatField(default=0, verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
                'ordering': ['create'],
            },
        ),
    ]
