# Generated by Django 5.2.6 on 2025-10-11 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmscores',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_from_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learn',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learns', to='user.teacher', verbose_name='مدرس'),
        ),
        migrations.AddField(
            model_name='headline',
            name='learn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='learn.learn'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='learn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='learn.learn', verbose_name='آموزش'),
        ),
        migrations.AddField(
            model_name='learnfilms',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='learn.headline', verbose_name='سرفصل'),
        ),
        migrations.AddField(
            model_name='learnfilms',
            name='scores',
            field=models.ManyToManyField(through='learn.FilmScores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmscores',
            name='film_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_to_set', to='learn.learnfilms'),
        ),
        migrations.AddIndex(
            model_name='learn',
            index=models.Index(fields=['-create'], name='learn_learn_create_430f19_idx'),
        ),
        migrations.AddIndex(
            model_name='headline',
            index=models.Index(fields=['create'], name='learn_headl_create_3e3ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='learnfilms',
            index=models.Index(fields=['create'], name='learn_learn_create_afdde3_idx'),
        ),
    ]
