# Generated by Django 5.2.6 on 2025-10-14 09:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_learn_users_register_registerlearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlearn',
            name='date_of_register',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
