# Generated by Django 5.2.6 on 2025-10-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_registerlearn_date_of_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlearn',
            name='learn_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_to_set', to='learn.learn'),
        ),
        migrations.AlterField(
            model_name='registerlearn',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_from_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
