# Generated by Django 5.2.6 on 2025-10-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_learn_users_register_and_more'),
    ]

    operations = [
    ]
    migrations.RenameField(
        model_name='learn',
        old_name='users_register',
        new_name='users',
    )
