# Generated by Django 5.2.6 on 2025-10-14 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20251014_1420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='users_register_new',
            field=models.ManyToManyField(related_name='learns', through='learn.RegisterLearn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learn',
            name='users_register',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربرها'),
        ),
    ]
