# Generated by Django 5.2.6 on 2025-10-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_learn_users_register_new_alter_learn_users_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='users_register',
        ),
    ]
