# Generated by Django 5.2.6 on 2025-10-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_remove_learn_users_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learn',
            old_name='users_register_new',
            new_name='users_register',
        ),
    ]
