# Generated by Django 5.2.6 on 2025-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_rename_users_register_new_learn_users_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='discount_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='precent_off',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
