# Generated by Django 5.2.6 on 2025-10-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_learn_discount_price_alter_learn_precent_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='description',
        ),
    ]
