# Generated by Django 5.2.6 on 2025-10-19 14:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_remove_learn_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, max_length=4000, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
