# Generated by Django 5.2.6 on 2025-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_learn_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
    ]
