# Generated by Django 5.2.6 on 2025-10-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_alter_learn_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
    ]
