# Generated by Django 5.2.6 on 2025-10-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_alter_learn_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnfilms',
            name='description',
        ),
    ]
