# Generated by Django 5.2.6 on 2025-10-22 12:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_remove_learnfilms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnfilms',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, max_length=1200, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
