# Generated by Django 5.2.6 on 2025-10-14 16:43

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0011_rename_users_register_new_learn_users_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='LearnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.learn')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learns', to='cart.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-create'], name='cart_order_create_01966b_idx'),
        ),
    ]
