# Generated by Django 5.2.6 on 2025-10-14 16:47

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_description'),
        ('learn', '0011_rename_users_register_new_learn_users_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnorder',
            name='learn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.learn', verbose_name='آموزش'),
        ),
        migrations.AlterField(
            model_name='learnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learns', to='cart.order', verbose_name='برای تراکنش:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
