# Generated by Django 5.2.6 on 2025-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_learnorder_learn_alter_learnorder_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnorder',
            options={'verbose_name': 'آموزش', 'verbose_name_plural': 'آموزش ها'},
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
