# Generated by Django 5.2.6 on 2025-10-23 09:00

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_learnorder_options_order_paid'),
        ('learn', '0018_learnfilms_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='کد تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('create', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('date_end', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا')),
                ('for_learns', models.ManyToManyField(related_name='off_codes', to='learn.learn')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
                'ordering': ['-create', 'date_end'],
                'indexes': [models.Index(fields=['-create'], name='cart_offcod_create_dd4612_idx'), models.Index(fields=['-date_end'], name='cart_offcod_date_en_e37318_idx')],
            },
        ),
    ]
