# Generated by Django 5.2.6 on 2025-10-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_offcode'),
        ('learn', '0018_learnfilms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='for_learns',
            field=models.ManyToManyField(related_name='off_codes', to='learn.learn', verbose_name='برای آموزش های'),
        ),
    ]
