# Generated by Django 5.2.6 on 2025-10-23 09:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_offcode_create_alter_offcode_date_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offcode',
            options={'ordering': ['-create'], 'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterField(
            model_name='offcode',
            name='create',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انقضا'),
        ),
    ]
