# Generated by Django 5.2.6 on 2025-10-23 09:13

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_offcode_options_alter_offcode_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='create',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 23, 9, 13, 47, 281179, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 23, 9, 13, 47, 281252, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
