# Generated by Django 5.2.6 on 2025-10-24 16:57

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_offcode_for_learns_alter_offcode_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='create',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 24, 16, 57, 6, 680409, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 24, 16, 57, 6, 680481, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
