# Generated by Django 5.2.6 on 2025-10-25 05:05

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_offcode_create_alter_offcode_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='create',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 25, 5, 5, 28, 948616, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2025, 10, 25, 5, 5, 28, 948704, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
