# Generated by Django 5.2.6 on 2025-10-25 14:30

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_offcode_create_alter_offcode_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='create',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا'),
        ),
    ]
