# Generated by Django 5.2.6 on 2025-09-26 14:45

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to='users/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'عادی'), ('TEACHER', 'مدرس'), ('BLOGER', 'بلاگر'), ('MANAGER', 'مدیر')], default='NORMAL', max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
