# Generated by Django 5.2.6 on 2025-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_learn_users_register_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learns_register',
            field=models.ManyToManyField(related_name='users', through='learn.RegisterLearn', to='learn.learn'),
        ),
    ]
