# Generated by Django 5.2.6 on 2025-10-11 09:34

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskForFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='learn.learnfilms', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_asks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال آموزش',
                'verbose_name_plural': 'سوالات آموزش',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='AnswerForFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('answer_by', models.CharField(choices=[('TH', 'معلم'), ('PO', 'پشتیبان')], default='TH', verbose_name='پاسخ داده شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_answers', to=settings.AUTH_USER_MODEL, verbose_name='مدرس یا پشتیبان')),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='comment.askforfilm', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='CommentForLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='پیام')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learn.learn', verbose_name='آموزش')),
                ('super_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='comment.commentforlearn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر برای آموزش',
                'verbose_name_plural': 'نظرات برای آموزش',
                'ordering': ['-create'],
            },
        ),
        migrations.AddIndex(
            model_name='askforfilm',
            index=models.Index(fields=['-create'], name='comment_ask_create_27edff_idx'),
        ),
        migrations.AddIndex(
            model_name='answerforfilm',
            index=models.Index(fields=['-create'], name='comment_ans_create_3194d4_idx'),
        ),
        migrations.AddIndex(
            model_name='commentforlearn',
            index=models.Index(fields=['-create'], name='comment_com_create_8fc22e_idx'),
        ),
    ]
