# Generated by Django 5.2.6 on 2025-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_commentforlearn_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerforfilm',
            name='answer_by',
            field=models.CharField(choices=[('TH', 'معلم'), ('PO', 'پشتیبان')], default='TH', max_length=2, verbose_name='پاسخ داده شده توسط'),
        ),
    ]
