# Generated by Django 5.2.6 on 2025-10-25 05:05

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('نظر', 'نظر'), ('انتقاد', 'انتقاد'), ('پیشنهاد', 'پیشنهاد')], max_length=10, verbose_name='دسته بندی')),
                ('message', models.TextField(max_length=500, verbose_name='پیام')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیک',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['-create'],
                'indexes': [models.Index(fields=['-create'], name='ticket_simp_create_0a966c_idx')],
            },
        ),
    ]
