# Generated by Django 5.2.6 on 2025-10-25 08:29

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleticket',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.CreateModel(
            name='TeacherTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('age', models.CharField(max_length=2, verbose_name='سن')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('address', models.TextField(max_length=500, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('bio', models.TextField(max_length=1000, verbose_name='بیوگرافی')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست مدرس',
                'verbose_name_plural': 'درخواست مدرسان',
                'ordering': ['-create'],
                'indexes': [models.Index(fields=['-create'], name='ticket_teac_create_e1c64e_idx')],
            },
        ),
    ]
