# Generated by Django 5.2.6 on 2025-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_collaborationticket_delete_teacherticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleticket',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('processing', 'درحال پردازش'), ('closed', 'بسته شده')], default="new", max_length=15, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
