# Generated by Django 5.2.6 on 2025-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_simpleticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleticket',
            options={'ordering': ['-create'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='simpleticket',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simpleticket',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('processing', 'درحال پردازش'), ('closed', 'بسته شده')], default='new', max_length=15, verbose_name='وضعیت'),
        ),
    ]
