# Generated by Django 5.2.6 on 2025-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_simpleticket_options_simpleticket_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleticket',
            name='message',
        ),
    ]
