# Generated by Django 5.2.6 on 2025-10-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_answerticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ticket.simpleticket', verbose_name='تیکت'),
        ),
    ]
