# Generated by Django 5.2.6 on 2025-10-25 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_answerticket_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleticket',
            options={'ordering': ['create'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.RemoveIndex(
            model_name='simpleticket',
            name='ticket_simp_create_0a966c_idx',
        ),
        migrations.AddIndex(
            model_name='simpleticket',
            index=models.Index(fields=['create'], name='ticket_simp_create_08e616_idx'),
        ),
    ]
