# Generated by Django 5.2.6 on 2025-10-25 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_simpleticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerticket',
            options={'ordering': ['create'], 'verbose_name': 'پاسخ به تیکت', 'verbose_name_plural': 'پاسخ ها به تیکت'},
        ),
        migrations.AlterModelOptions(
            name='simpleticket',
            options={'ordering': ['-create'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.RemoveIndex(
            model_name='answerticket',
            name='ticket_answ_create_fd32ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='simpleticket',
            name='ticket_simp_create_08e616_idx',
        ),
        migrations.AddIndex(
            model_name='answerticket',
            index=models.Index(fields=['create'], name='ticket_answ_create_b318b0_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleticket',
            index=models.Index(fields=['-create'], name='ticket_simp_create_0a966c_idx'),
        ),
    ]
